// tslint:disable-next-line: max-line-length
// Link to resource types: https://ordercloud.visualstudio.com/OC-Marketplace/_git/OC-Marketplace?path=%2Fsrc%2FMiddleware%2Fintegrations%2Fordercloud.integrations.cms%2FModels%2FResourceType.cs
export enum ResourceType {
    Catalogs = 'Catalogs',
    Categories = 'Categories',
    Products = 'Products',
    PriceSchedules = 'PriceSchedules',
    ProductFacets = 'ProductFacets',
    Specs = 'Specs',
    SecurityProfiles = 'SecurityProfiles',
    PasswordResets = 'PasswordResets',
    OpenIdConnects = 'OpenIdConnects',
    ImpersonationConfigs = 'ImpersonationConfigs',
    Buyers = 'Buyers',
    Users = 'Users',
    UserGroups = 'UserGroups',
    Addresses = 'Addresses',
    CostCenters = 'CostCenters',
    CreditCards = 'CreditCards',
    SpendingAccounts = 'SpendingAccounts',
    SupplierUsers = 'SupplierUsers',
    SupplierUserGroups = 'SupplierUserGroups',
    SupplierAddresses = 'SupplierAddresses',
    Promotions = 'ApproPromotionsvalRules',
    AdminUsers = 'AdminUsers',
    AdminAddresses = 'AdminAddresses',
    AdminUserGroups = 'AdminUserGroups',
    MessageSenders = 'MessageSenders',
    Webhooks = 'Webhooks',
    ApiClients = 'ApiClients',
    Incrementors = 'Incrementors',
    IntegrationEvents = 'IntegrationEvents',
    XpIndices = 'XpIndices',

}
