export const ASSET_TYPE_IMAGE = 'Image';
export type ASSET_TYPE_IMAGE = typeof ASSET_TYPE_IMAGE;

export const ASSET_TYPE_TEXT = 'Text';
export type ASSET_TYPE_TEXT = typeof ASSET_TYPE_TEXT;

export const ASSET_TYPE_AUDIO = 'Audio';
export type ASSET_TYPE_AUDIO = typeof ASSET_TYPE_AUDIO;

export const ASSET_TYPE_VIDEO = 'Video';
export type ASSET_TYPE_VIDEO = typeof ASSET_TYPE_VIDEO;

export const ASSET_TYPE_PRESENTATION = 'Presentation';
export type ASSET_TYPE_PRESENTATION = typeof ASSET_TYPE_PRESENTATION;

export const ASSET_TYPE_SPREADSHEET = 'SpreadSheet';
export type ASSET_TYPE_SPREADSHEET = typeof ASSET_TYPE_SPREADSHEET;

export const ASSET_TYPE_PDF = 'PDF';
export type ASSET_TYPE_PDF = typeof ASSET_TYPE_PDF;

export const ASSET_TYPE_COMPRESSED = 'Compressed';
export type ASSET_TYPE_COMPRESSED = typeof ASSET_TYPE_COMPRESSED;

export const ASSET_TYPE_CODE = 'Code';
export type ASSET_TYPE_CODE = typeof ASSET_TYPE_CODE;

export const ASSET_TYPE_JSON = 'JSON';
export type ASSET_TYPE_JSON = typeof ASSET_TYPE_JSON;

export const ASSET_TYPE_MARKUP = 'Markup';
export type ASSET_TYPE_MARKUP = typeof ASSET_TYPE_MARKUP;

export const ASSET_TYPE_UNKNOWN = 'Unknown';
export type ASSET_TYPE_UNKNOWN = typeof ASSET_TYPE_UNKNOWN;

export type ASSET_TYPES =
  | ASSET_TYPE_IMAGE
  | ASSET_TYPE_TEXT
  | ASSET_TYPE_AUDIO
  | ASSET_TYPE_VIDEO
  | ASSET_TYPE_PRESENTATION
  | ASSET_TYPE_SPREADSHEET
  | ASSET_TYPE_PDF
  | ASSET_TYPE_COMPRESSED
  | ASSET_TYPE_CODE
  | ASSET_TYPE_MARKUP
  | ASSET_TYPE_JSON
  | ASSET_TYPE_UNKNOWN;

const DEFAULT_ASSET_TYPES: ASSET_TYPES[] = [
  ASSET_TYPE_IMAGE,
  ASSET_TYPE_TEXT,
  ASSET_TYPE_AUDIO,
  ASSET_TYPE_VIDEO,
  ASSET_TYPE_PRESENTATION,
  ASSET_TYPE_SPREADSHEET,
  ASSET_TYPE_PDF,
  ASSET_TYPE_COMPRESSED,
  ASSET_TYPE_CODE,
  ASSET_TYPE_MARKUP,
  ASSET_TYPE_JSON,
  ASSET_TYPE_UNKNOWN,
];

export const ASSET_TYPE = {
  [ASSET_TYPE_IMAGE]: ASSET_TYPE_IMAGE,
  [ASSET_TYPE_TEXT]: ASSET_TYPE_TEXT,
  [ASSET_TYPE_AUDIO]: ASSET_TYPE_AUDIO,
  [ASSET_TYPE_VIDEO]: ASSET_TYPE_VIDEO,
  [ASSET_TYPE_PRESENTATION]: ASSET_TYPE_PRESENTATION,
  [ASSET_TYPE_SPREADSHEET]: ASSET_TYPE_SPREADSHEET,
  [ASSET_TYPE_PDF]: ASSET_TYPE_PDF,
  [ASSET_TYPE_COMPRESSED]: ASSET_TYPE_COMPRESSED,
  [ASSET_TYPE_CODE]: ASSET_TYPE_CODE,
  [ASSET_TYPE_MARKUP]: ASSET_TYPE_MARKUP,
  [ASSET_TYPE_JSON]: ASSET_TYPE_JSON,
  [ASSET_TYPE_UNKNOWN]: ASSET_TYPE_UNKNOWN,
};

export default DEFAULT_ASSET_TYPES;
