import 'tinymce/tinymce';
import '../../../../plugin/dist/plugin.min.js';
import { HeadStartSDK } from '@ordercloud/headstart-sdk';
import * as HeadStartSDKInstance from '@ordercloud/headstart-sdk';

HeadStartSDKInstance.Configuration.Set({
  baseApiUrl: 'https://marketplace-middleware-test.azurewebsites.net',
});
HeadStartSDK.Tokens.SetAccessToken(
  'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3IiOiJyd2F0dDQxMTA2IiwiY2lkIjoiN2UwZmQ2MmItOWRkOS00OTM5LTllMGItMjZkODgyZmMzNTA4IiwiaW1wIjoiMTAwNSIsInUiOiIzMTE4MzYzIiwidXNydHlwZSI6InN1cHBsaWVyIiwicm9sZSI6WyJBc3NldEFkbWluIiwiQnV5ZXJSZWFkZXIiLCJEb2N1bWVudEFkbWluIiwiTWVBZG1pbiIsIk9yZGVyQWRtaW4iLCJQYXNzd29yZFJlc2V0IiwiUHJpY2VTY2hlZHVsZUFkbWluIiwiUHJpY2VTY2hlZHVsZVJlYWRlciIsIlByb2R1Y3RBZG1pbiIsIlByb2R1Y3RSZWFkZXIiLCJQcm9tb3Rpb25BZG1pbiIsIlByb21vdGlvblJlYWRlciIsIlNjaGVtYUFkbWluIiwiU2V0U2VjdXJpdHlQcm9maWxlIiwiU2hpcG1lbnRBZG1pbiIsIlN1cHBsaWVyQWRkcmVzc0FkbWluIiwiU3VwcGxpZXJBZGRyZXNzUmVhZGVyIiwiU3VwcGxpZXJBZG1pbiIsIlN1cHBsaWVyUmVhZGVyIiwiU3VwcGxpZXJVc2VyQWRtaW4iLCJTdXBwbGllclVzZXJSZWFkZXIiXSwiaXNzIjoiaHR0cHM6Ly9hdXRoLm9yZGVyY2xvdWQuaW8iLCJhdWQiOiJodHRwczovL2FwaS5vcmRlcmNsb3VkLmlvIiwiZXhwIjoxNTk4MzEzMjE0LCJuYmYiOjE1OTgyODQ0MTR9.Di60UPadfC9AjPGUTaXK1XHxe4n5VBVyk0eBZGALZMM'
);
